/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppGuardRouteImport } from './routes/app.guard'
import { Route as AppQuoteRouteImport } from './routes/app.quote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardRoute = AppGuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => AppRoute,
} as any)
const AppQuoteRoute = AppQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/compare': typeof AppCompareRoute
  '/app/guard': typeof AppGuardRoute
  '/app/quote': typeof AppQuoteRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/activity': typeof AppActivityRoute
  '/app/compare': typeof AppCompareRoute
  '/app/guard': typeof AppGuardRoute
  '/app/quote': typeof AppQuoteRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/compare': typeof AppCompareRoute
  '/app/guard': typeof AppGuardRoute
  '/app/quote': typeof AppQuoteRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/compare'
    | '/app/guard'
    | '/app/quote'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/activity'
    | '/app/compare'
    | '/app/guard'
    | '/app/quote'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/compare'
    | '/app/guard'
    | '/app/quote'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guard': {
      id: '/app/guard'
      path: '/guard'
      fullPath: '/app/guard'
      preLoaderRoute: typeof AppGuardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quote': {
      id: '/app/quote'
      path: '/quote'
      fullPath: '/app/quote'
      preLoaderRoute: typeof AppQuoteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCompareRoute: typeof AppCompareRoute
  AppGuardRoute: typeof AppGuardRoute
  AppQuoteRoute: typeof AppQuoteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCompareRoute: AppCompareRoute,
  AppGuardRoute: AppGuardRoute,
  AppQuoteRoute: AppQuoteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
